### ISSUE TITLE
introspection: base classes

### ISSUE THREAD

**Issue by jneuendorf** [arximboldi/heterarchy#6]
As of now, it is impossible to find the base class(es) of a subclass. The existing introspection functions `mro`, `inherited` and `hierarchy` cannot be used for task (if I am right).
In another project of mine I need this feature for generating a UML class diagram.

It would be nice to have a `__bases__` attribute at least on those classes classes that `extend multi(...)`.

The `bases` only get passed into the `multi` function so I guess the bases must be attached there are passed along.

**Comment by arximboldi** [comment]
Aha! Yeah, good question.

I agree that the generated classes would need a `__bases__` attribute. But the way it works now the same generated class can be used in two places with different bases if the same linearization is produced from two inheritance diagrams (I still need to see if there is a case where this is actually possible).

If that was no problem or we found a way to avoid it, I'd suggest we add the `__bases__` attribute and provide a `bases` free function that is smart enough to also return the value for normally inherited stuff.

**Comment by jneuendorf** [comment]
You mean
`The multi function memoizes its results such that identity is maintained, implying multi X, Y is multi X, Y.`, right?

Is that memorization made for performance reasons or is there a scenario where one would expect to behave like that? If performance is the reason I think we could just change it because the `multi` call happens upon class initialization which is only happening once per class.

A `bases` function would totally fit in the current introspection code so I'd also provide that.

**Comment by arximboldi** [comment]
Yeah, it is because of the memoization. I still believe that the memoization is useful, because otherwise you can get an quadratic number of generated classes. Without it, every class in the linearization would be re-generated in every inherited class.

However, there is another solution, which is to add an intermediate class that inherits from what `generate ...` produces and stores the bases. This can be memoized too I think.

**Comment by arximboldi** [comment]
Nah, I am overthinking it, I believe that there is no way to produce the same linearization inheriting from different bases. I mean, one can produce the same sub-linearizations, but the __bases__ thingy is to be queried only from the named class (what inherits from `multi ...`), so we are fine I think.

If you think that this is a fun project for you, go ahead and give it a try. Otherwise I can try to do it myself.

**Comment by jneuendorf** [comment]
What seems to work is

```coffee
exports.multi = (bases...) ->
  cls = generate merge map(bases, mro).concat [bases]
  cls.__bases__ = bases
  cls
```

I can create a PR 😉
